server:
  port: 8080
  servlet:
    context-path: /mydemo
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.236.37:3306/mydemo?useSSl=true
    username: root
    password: 13486059134chen

  jpa:
      show-sql: true
      open-in-view: true
